

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CourseWorkClinic.App_Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class ClinicEntities : DbContext
{
    public ClinicEntities()
        : base("name=ClinicEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<sysdiagrams> sysdiagrams { get; set; }

    public DbSet<UserProfile> UserProfile { get; set; }

    public DbSet<webpages_Membership> webpages_Membership { get; set; }

    public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }

    public DbSet<webpages_Roles> webpages_Roles { get; set; }

    public DbSet<Адреса> Адреса { get; set; }

    public DbSet<Врачи> Врачи { get; set; }

    public DbSet<Дни_недели> Дни_недели { get; set; }

    public DbSet<Направление> Направление { get; set; }

    public DbSet<Пациенты> Пациенты { get; set; }

    public DbSet<Пользователи> Пользователи { get; set; }

    public DbSet<Прием> Прием { get; set; }

    public DbSet<Расписание> Расписание { get; set; }

    public DbSet<Расписание_врачей> Расписание_врачей { get; set; }

    public DbSet<Сотрудники> Сотрудники { get; set; }

    public DbSet<Специальности> Специальности { get; set; }

    public DbSet<Список_врачей1> Список_врачей1Set { get; set; }

    public DbSet<Таблица_участков> Таблица_участков { get; set; }


    public virtual int Refresh_pers()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Refresh_pers");
    }

}

}

