//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkClinic.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врачи
    {
        public Врачи()
        {
            this.Прием = new HashSet<Прием>();
            this.Направление = new HashSet<Направление>();
            this.Направление1 = new HashSet<Направление>();
            this.Участки = new HashSet<Участки>();
            this.Расписание = new HashSet<Расписание>();
        }
    
        public System.Guid ID_врача { get; set; }
        public int Код_специальности { get; set; }
        public System.Guid ID_сотрудника { get; set; }
    
        public virtual ICollection<Прием> Прием { get; set; }
        public virtual Специальности Специальности { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual ICollection<Направление> Направление { get; set; }
        public virtual ICollection<Направление> Направление1 { get; set; }
        public virtual ICollection<Участки> Участки { get; set; }
        public virtual ICollection<Расписание> Расписание { get; set; }
    }
}
