
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CourseWorkClinic.App_Data
{

using System;
    using System.Collections.Generic;
    
public partial class Направление
{

    public Направление()
    {

        this.Прием = new HashSet<Прием>();

    }


    public System.Guid C_направления { get; set; }

    public System.Guid ID_врача { get; set; }

    public System.Guid ID_врача_ведущего_прием { get; set; }

    public System.Guid ID_пациента { get; set; }



    public virtual Врачи Врачи { get; set; }

    public virtual Врачи Врачи1 { get; set; }

    public virtual Пациенты Пациенты { get; set; }

    public virtual ICollection<Прием> Прием { get; set; }

}

}
