//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkClinic.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациенты
    {
        public Пациенты()
        {
            this.Направление = new HashSet<Направление>();
            this.Прием = new HashSet<Прием>();
        }
    
        public System.Guid ID_пациента { get; set; }
        public string C__полиса { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public Nullable<System.DateTime> Дата_смерти { get; set; }
        public int Код_адреса { get; set; }
    
        public virtual Адреса Адреса { get; set; }
        public virtual ICollection<Направление> Направление { get; set; }
        public virtual ICollection<Прием> Прием { get; set; }
    }
}
