//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkClinic.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прием
    {
        public System.Guid ID_приема { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<double> Длительность { get; set; }
        public string Диагноз { get; set; }
        public string Рецепт { get; set; }
        public string Примечание { get; set; }
        public Nullable<System.Guid> C__направления { get; set; }
        public System.Guid ID_врача { get; set; }
        public System.Guid ID_пациента { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Направление Направление { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
