//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkClinic.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public System.Guid ID_записи { get; set; }
        public string Неделя { get; set; }
        public System.TimeSpan Время_начала { get; set; }
        public System.TimeSpan Время_окончания { get; set; }
        public int C__кабинета { get; set; }
        public System.Guid ID_врача { get; set; }
        public int Код_дня { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Дни_недели Дни_недели { get; set; }
    }
}
