
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CourseWorkClinic.App_Data
{

using System;
    using System.Collections.Generic;
    
public partial class Сотрудники
{

    public Сотрудники()
    {

        this.Врачи = new HashSet<Врачи>();

    }


    public System.Guid ID_сотрудника { get; set; }

    public string Фамилия { get; set; }

    public string Имя { get; set; }

    public string Отчество { get; set; }



    public virtual ICollection<Врачи> Врачи { get; set; }

}

}
